interface MorseCode {
  letter: string;
  code: string;
}

export const morses: MorseCode[] = [
  { letter: "A", code: ".-" },
  { letter: "B", code: "-..." },
  { letter: "C", code: "-.-." },
  { letter: "D", code: "-.." },
  { letter: "E", code: "." },
  { letter: "F", code: "..-." },
  { letter: "G", code: "--." },
  { letter: "H", code: "...." },
  { letter: "I", code: ".." },
  { letter: "J", code: ".---" },
  { letter: "K", code: "-.-" },
  { letter: "L", code: ".-.." },
  { letter: "M", code: "--" },
  { letter: "N", code: "-." },
  { letter: "O", code: "---" },
  { letter: "P", code: ".--." },
  { letter: "Q", code: "--.-" },
  { letter: "R", code: ".-." },
  { letter: "S", code: "..." },
  { letter: "T", code: "-" },
  { letter: "U", code: "..-" },
  { letter: "V", code: "...-" },
  { letter: "W", code: ".--" },
  { letter: "X", code: "-..-" },
  { letter: "Y", code: "-.--" },
  { letter: "Z", code: "--.." },
  { letter: "1", code: ".----" },
  { letter: "2", code: "..---" },
  { letter: "3", code: "...--" },
  { letter: "4", code: "....-" },
  { letter: "5", code: "....." },
  { letter: "6", code: "-...." },
  { letter: "7", code: "--..." },
  { letter: "8", code: "---.." },
  { letter: "9", code: "----." },
  { letter: "0", code: "-----" },
  { letter: ".", code: ".-.-.-" },
  { letter: ",", code: "--..--" },
  { letter: "?", code: "..--.." },
  { letter: "!", code: "-.-.--" },
];
